### ISSUE TITLE
save the state

### ISSUE THREAD

**Issue by nuke1984** [x42/mclk.lv2#3]
is there a way to save state of the mclk.lv2 plugin in Carla??
in particular i need to save a state about BPM (free tunning mode) so i can recall a particultar state of the BPM parameter via midi program change.

**Comment by x42** [comment]
That is just a normal control port, it's the host's job to save/restore the value.

@falktx is there anything special that a user has to do, for Carla to save plugin state? Here specifically:
https://github.com/x42/mclk.lv2/blob/4f9d423b5d374d4b4a2c1bdd49257f36a77cdb10/lv2ttl/mclk.ttl.in#L72-L82

**Comment by falkTX** [comment]
that should work as-is.

**Comment by nuke1984** [comment]
Thanks for the quick answers.
Actually "Save State" is greyed out for mclk.lv2 in Carla interface.
mclk.lv2 is compiled from source in Ubuntu 22.04.
other plugins show correctly the Save State option.
Am I missing something?

![Screenshot from 2023-12-08 21-27-41](https://github.com/x42/mclk.lv2/assets/153304141/db637b7f-08d7-43fd-ade7-2682b8c5b86a)

**Comment by falkTX** [comment]
that is for plugin-side presets, carla does not support saving lv2 presets at this point.

**Comment by nuke1984** [comment]
OK, understand. thanks for the clarification.

**Comment by nuke1984** [comment]
@x42 is there a way to integrate plugin-side presets inside mclk.lv2 plugin? or even a way to recall a BPM setting via MIDI program change?

**Comment by x42** [comment]
Nope. presets are managed by the host, not the plugin.

This works just fine in other hosts. I suggest to file a feature request for Carla to support plugin presets.

**Comment by nuke1984** [comment]
ok @x42 , hope to see plugin preset support on Carla soon @falkTX .
by the way thanks Robin and Filipe for the incredible works on Linux audio.
